
server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://db.newlecture.com:3306/mineurs?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mineurs
    password: 20240129


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: com.newlecmineursprj.entity

