
server:
  port:

spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  type-aliases-package:

logging:
  level:
    com:
      newlecmineursprj:
        repository:
          TRACE
    
