server:
  port:

spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: com.newlecmineursprj.entity

logging:
  level:
    com:
      newlecmineursprj:
        repository:
          TRACE

